services:
  postgresdb:
    image: postgres:14.8-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
      - POSTGRES_CREATE_DB=true
    volumes: 
      - postgres-data:/var/lib/postgresql/data

  app:
    image: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - LISTEN_ADDRESS_HTTP=0.0.0.0:8080 
      - DB_URL=postgres://postgres:postgres@postgresdb:5432/test?sslmode=disable 
      - PRODUCTION=true 
      - LOG_JSON=true 
      - LOG_LEVEL=trace
      - JWT_SIGN_KEY=qwsedrftgyuiasdfghjzxcvbnmqaszx4erfvyhnujk 
    restart: on-failure
    depends_on:
      - postgresdb

volumes:
  postgres-data:
    